### ISSUE TITLE
Make a first release

### ISSUE THREAD

**Issue by Chris2011** [Xyo/Netbeans-LaTeX-Plugin#1]
Hey,

I really would like to use your plugin so can you make a first alpha or beta release that I can have a look, how it is? Would be great :)

Regards

Chris

**Comment by Xyo** [comment]
This was a school project, and is unfinished and unsupported. Sorry!

**Comment by Chris2011** [comment]
But does it work?

**Comment by Xyo** [comment]
If I remember correctly, it will correctly parse and compile, and has a basic document outline. It doesn't have syntax highlighting or any other useful features that other editors have.

**Comment by Chris2011** [comment]
Hm ok. Thx.
